version: "3.8"
services:
  backend:
    build: .
    container_name: voting-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/votingDB
      - JWT_SECRET=your_secret_key
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo:latest
    container_name: voting-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
